version: "2.27"

services:
  # (Optional)It's not required if you already have a postgres database which version is 12
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    volumes:
      - "../localstack-data/sqldata:/var/lib/postgresql/data"
  # (Optional)adminer is GUI for Database management
  adminer:
    image: adminer
    restart: always
    ports:
      - 55008:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
  backend:
    image: hongyu/ticket-master:latest
    # command: sleep infinity
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - "./log:/var/log"
      - "./config.yml:/app/config.yml:ro"
  